services:
  electrum:
    build:
      context: .
      args:
        - ELECTRUM_VERSION=4.2.1
        - ELECTRUM_CHECKSUM_SHA512=980dfab33f7ae1dfb2f9e77272d00919224b7d4267d5f9a298ba082779ef5cc10260926dd5ad75f6ff54c1b5f451bbe4ee3d0c3908db5b54b3546cb5e9ec49f6
    container_name: electrum
    ports:
      - 127.0.0.1:7000:7000
    environment:
      - ELECTRUM_USER=electrum
      - ELECTRUM_PASSWORD=changeme
      - ELECTRUM_NETWORK=regtest
    volumes:
        - ../electrum:/data
