services:
  electrum:
    build:
      context: .
      args:
        - ELECTRUM_VERSION=4.5.8
        - ELECTRUM_CHECKSUM_SHA512=ccf45dc5e3a615d446e0714ddaa9ef74b96829bdf9a5236e18efff5f014ca18c48502a375ec98c9bc170f1db69e846b7015ca715b9cac8d77afde9f1939bc403
    container_name: electrum
    ports:
      - 127.0.0.1:7000:7000
    environment:
      - ELECTRUM_RPCUSER=electrum
      - ELECTRUM_RPCPASSWORD=changeme
      - ELECTRUM_NETWORK=regtest
    volumes:
        - ../electrum:/data
