services:
  electrum:
    build:
      context: .
      args:
        - ELECTRUM_VERSION=${ELECTRUM_VERSION}
        - ELECTRUM_CHECKSUM_SHA512=${ELECTRUM_CHECKSUM_SHA512}
        - ELECTRUM_RPCPORT=17000
    container_name: electrum
    ports:
      - 127.0.0.1:7000:17000
    environment:
      - ELECTRUM_RPCUSER=electrum
      - ELECTRUM_RPCPASSWORD=changeme
      - ELECTRUM_NETWORK=regtest
    volumes:
      - ./.data:/home/electrum/.electrum:z
    healthcheck:
      test: [ "CMD", "electrum", "--regtest", "getinfo" ]
      interval: 3s
      retries: 20